//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int billsID { get; set; }
        public System.DateTime date { get; set; }
        public int status { get; set; }
        public int customerID { get; set; }
        public string info { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
