//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Bills = new HashSet<Bills>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int customerID { get; set; }
        public string customerCompanyName { get; set; }
        public string customerGSM { get; set; }
        public string customerPhone { get; set; }
        public string customerName { get; set; }
        public string customerAddress { get; set; }
        public string customerDescription { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> countryID { get; set; }
        public string taxNumber { get; set; }
        public string tcNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills> Bills { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
