//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentForemans
    {
        public int depForeID { get; set; }
        public int userID { get; set; }
        public int departmentID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Users Users { get; set; }
    }
}
