//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int documentID { get; set; }
        public string documentPath { get; set; }
        public int reconciliationsDocumentID { get; set; }
    
        public virtual ReconciliationsDocument ReconciliationsDocument { get; set; }
    }
}
