//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeRoles()
        {
            this.EmployeeRolePerformances = new HashSet<EmployeeRolePerformances>();
            this.Employees = new HashSet<Employees>();
            this.ProductEmpRoles = new HashSet<ProductEmpRoles>();
            this.RecipeEmployees = new HashSet<RecipeEmployees>();
        }
    
        public int empRoleID { get; set; }
        public string empRoleName { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<double> salaryFood { get; set; }
        public Nullable<double> salaryService { get; set; }
        public Nullable<double> salarySSK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeRolePerformances> EmployeeRolePerformances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEmpRoles> ProductEmpRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeEmployees> RecipeEmployees { get; set; }
    }
}
