//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaries
    {
        public int empSalaryID { get; set; }
        public int empID { get; set; }
        public double salary { get; set; }
        public System.DateTime salaryDate { get; set; }
        public double salaryService { get; set; }
        public double salaryFood { get; set; }
        public double salarySSK { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
