//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeConsents
    {
        public int empConsentID { get; set; }
        public int empID { get; set; }
        public string consDescription { get; set; }
        public System.DateTime consStartDate { get; set; }
        public System.DateTime consFinishDate { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
