//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.EmployeeConsents = new HashSet<EmployeeConsents>();
            this.EmployeeSalaries = new HashSet<EmployeeSalaries>();
            this.MachineEmployees = new HashSet<MachineEmployees>();
            this.WorMachEmployees = new HashSet<WorMachEmployees>();
        }
    
        public int empID { get; set; }
        public string empName { get; set; }
        public Nullable<System.DateTime> empStartDate { get; set; }
        public string empPhone { get; set; }
        public string empAddress { get; set; }
        public bool empStatus { get; set; }
        public Nullable<System.DateTime> empQuitDate { get; set; }
        public int empRoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeConsents> EmployeeConsents { get; set; }
        public virtual EmployeeRoles EmployeeRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalaries> EmployeeSalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineEmployees> MachineEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorMachEmployees> WorMachEmployees { get; set; }
    }
}
