//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int expenseID { get; set; }
        public string expenseName { get; set; }
        public double expensePrice { get; set; }
        public System.DateTime expenseDate { get; set; }
    }
}
