//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineEmployees
    {
        public int machEmpID { get; set; }
        public int empID { get; set; }
        public int machineID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Machines Machines { get; set; }
    }
}
