//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineFaults
    {
        public int faultID { get; set; }
        public int machineID { get; set; }
        public string faultContent { get; set; }
        public System.DateTime faultDate { get; set; }
        public double faultCost { get; set; }
        public bool status { get; set; }
    
        public virtual Machines Machines { get; set; }
    }
}
