//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialStocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialStocks()
        {
            this.MaterialStockRecords = new HashSet<MaterialStockRecords>();
        }
    
        public int materialStockID { get; set; }
        public int materialID { get; set; }
        public double stockCount { get; set; }
        public double warningAmount { get; set; }
    
        public virtual Materials Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStockRecords> MaterialStockRecords { get; set; }
    }
}
