//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialStockRecords
    {
        public int mstockRecordID { get; set; }
        public int materialStockID { get; set; }
        public System.DateTime stockRecordDate { get; set; }
        public double stockRecordCount { get; set; }
        public bool stockRecordOperation { get; set; }
        public Nullable<int> worderID { get; set; }
    
        public virtual MaterialStocks MaterialStocks { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
