//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class arisanerpEntities : DbContext
    {
        public arisanerpEntities()
            : base("name=arisanerpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreement> Agreement { get; set; }
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<DepartmentForemans> DepartmentForemans { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<DepartmentTypes> DepartmentTypes { get; set; }
        public virtual DbSet<EmployeeConsents> EmployeeConsents { get; set; }
        public virtual DbSet<EmployeeRolePerformances> EmployeeRolePerformances { get; set; }
        public virtual DbSet<EmployeeRoles> EmployeeRoles { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeeSalaries> EmployeeSalaries { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<MachineEmployees> MachineEmployees { get; set; }
        public virtual DbSet<MachineFaults> MachineFaults { get; set; }
        public virtual DbSet<MachineMolds> MachineMolds { get; set; }
        public virtual DbSet<Machines> Machines { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialStockRecords> MaterialStockRecords { get; set; }
        public virtual DbSet<MaterialStocks> MaterialStocks { get; set; }
        public virtual DbSet<MoldCounts> MoldCounts { get; set; }
        public virtual DbSet<MoldNumbers> MoldNumbers { get; set; }
        public virtual DbSet<Molds> Molds { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Parcel> Parcel { get; set; }
        public virtual DbSet<ProductBox> ProductBox { get; set; }
        public virtual DbSet<ProductEmpRoles> ProductEmpRoles { get; set; }
        public virtual DbSet<ProductMaterials> ProductMaterials { get; set; }
        public virtual DbSet<ProductModels> ProductModels { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductStockBarcodeOut> ProductStockBarcodeOut { get; set; }
        public virtual DbSet<ProductStockRecords> ProductStockRecords { get; set; }
        public virtual DbSet<ProductStocks> ProductStocks { get; set; }
        public virtual DbSet<RecipeEmployees> RecipeEmployees { get; set; }
        public virtual DbSet<RecipeExpenses> RecipeExpenses { get; set; }
        public virtual DbSet<RecipeMaterials> RecipeMaterials { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<Reconciliations> Reconciliations { get; set; }
        public virtual DbSet<subOrders> subOrders { get; set; }
        public virtual DbSet<subWork> subWork { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Units> Units { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WordepMachines> WordepMachines { get; set; }
        public virtual DbSet<WorDepMachMolds> WorDepMachMolds { get; set; }
        public virtual DbSet<WorderDepartments> WorderDepartments { get; set; }
        public virtual DbSet<WorderEmpDayOffs> WorderEmpDayOffs { get; set; }
        public virtual DbSet<WorderRecipes> WorderRecipes { get; set; }
        public virtual DbSet<WorkOrders> WorkOrders { get; set; }
        public virtual DbSet<WorMachEmployees> WorMachEmployees { get; set; }
        public virtual DbSet<WorMachEmpWorks> WorMachEmpWorks { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<ReconciliationsDocument> ReconciliationsDocument { get; set; }
    }
}
