//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoldCounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoldCounts()
        {
            this.WorDepMachMolds = new HashSet<WorDepMachMolds>();
        }
    
        public int moldCountID { get; set; }
        public int moldID { get; set; }
        public int moldNoID { get; set; }
        public int moldCount { get; set; }
    
        public virtual MoldNumbers MoldNumbers { get; set; }
        public virtual Molds Molds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorDepMachMolds> WorDepMachMolds { get; set; }
    }
}
