//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.subOrders = new HashSet<subOrders>();
            this.WorkOrders = new HashSet<WorkOrders>();
        }
    
        public int orderID { get; set; }
        public string orderName { get; set; }
        public Nullable<int> orderQuantity { get; set; }
        public System.DateTime orderDate { get; set; }
        public Nullable<System.DateTime> orderDeliveryDate { get; set; }
        public int orderStatus { get; set; }
        public int customerID { get; set; }
        public string orderDescription { get; set; }
        public int orderCounter { get; set; }
        public Nullable<bool> orderConfirmation { get; set; }
        public Nullable<int> orderType { get; set; }
        public int orderStage { get; set; }
    
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subOrders> subOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrders> WorkOrders { get; set; }
    }
}
