//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBox
    {
        public int ProductBoxID { get; set; }
        public int workOrderId { get; set; }
        public bool productType { get; set; }
        public int moldNoId { get; set; }
        public int modelNoId { get; set; }
        public int ParcelBarcodeID { get; set; }
        public int ProductBoxBarcode { get; set; }
        public Nullable<int> orderID { get; set; }
    }
}
