//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockRecords
    {
        public int pstockRecordID { get; set; }
        public int productStockID { get; set; }
        public System.DateTime stockRecordDate { get; set; }
        public int stockRecordCount { get; set; }
        public bool stockRecordOperation { get; set; }
        public Nullable<int> worderID { get; set; }
        public int barcode { get; set; }
        public int modelNoID { get; set; }
        public int moldNoID { get; set; }
    
        public virtual MoldNumbers MoldNumbers { get; set; }
        public virtual ProductModels ProductModels { get; set; }
        public virtual ProductStocks ProductStocks { get; set; }
        public virtual subWork subWork { get; set; }
    }
}
