//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStocks()
        {
            this.ProductStockRecords = new HashSet<ProductStockRecords>();
        }
    
        public int productStockID { get; set; }
        public int productID { get; set; }
        public int stockCount { get; set; }
        public bool stockType { get; set; }
        public int modelID { get; set; }
        public int moldNoID { get; set; }
    
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStockRecords> ProductStockRecords { get; set; }
    }
}
