//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipes()
        {
            this.RecipeEmployees = new HashSet<RecipeEmployees>();
            this.RecipeExpenses = new HashSet<RecipeExpenses>();
            this.RecipeMaterials = new HashSet<RecipeMaterials>();
            this.WorderRecipes = new HashSet<WorderRecipes>();
        }
    
        public int recipeID { get; set; }
        public string recipeName { get; set; }
        public int productID { get; set; }
        public int productionQuantity { get; set; }
        public double productWeight { get; set; }
        public double exchangeRate { get; set; }
        public double recipeTotalPrice { get; set; }
        public bool recipeType { get; set; }
        public double singProdCost { get; set; }
        public double materialsTotalPrice { get; set; }
        public double expensesTotalPrice { get; set; }
        public double boilCount { get; set; }
        public double employeesTotalPrice { get; set; }
        public bool productType { get; set; }
        public int modelID { get; set; }
        public int moldNoID { get; set; }
    
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeEmployees> RecipeEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeExpenses> RecipeExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeMaterials> RecipeMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorderRecipes> WorderRecipes { get; set; }
    }
}
