//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeEmployees
    {
        public int rempID { get; set; }
        public int recipeID { get; set; }
        public int empRoleID { get; set; }
        public double rempSalary { get; set; }
        public double rempSalaryService { get; set; }
        public double rempSalaryFood { get; set; }
        public double rempSalarySSK { get; set; }
        public int empsNumber { get; set; }
    
        public virtual EmployeeRoles EmployeeRoles { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
