//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconciliations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reconciliations()
        {
            this.ReconciliationsDocument = new HashSet<ReconciliationsDocument>();
        }
    
        public int reconID { get; set; }
        public string title { get; set; }
        public string country { get; set; }
        public string taxNumber { get; set; }
        public int documentNumber { get; set; }
        public double amountService { get; set; }
        public string phoneNumber { get; set; }
        public string tcNumber { get; set; }
        public string representative { get; set; }
        public string customer { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> processStatus { get; set; }
        public int agreementID { get; set; }
        public bool sentStatus { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReconciliationsDocument> ReconciliationsDocument { get; set; }
    }
}
