//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subOrders()
        {
            this.subWork = new HashSet<subWork>();
        }
    
        public int subOrderID { get; set; }
        public int productID { get; set; }
        public int modelID { get; set; }
        public int modelNoID { get; set; }
        public int orderQuantityNumber { get; set; }
        public double productUnitPrice { get; set; }
        public int recipeID { get; set; }
        public int orderID { get; set; }
        public int sumiProductCounter { get; set; }
        public int subOrderStage { get; set; }
        public Nullable<int> billsID { get; set; }
    
        public virtual MoldNumbers MoldNumbers { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual ProductModels ProductModels { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subWork> subWork { get; set; }
    }
}
