//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subWork()
        {
            this.ProductStockRecords = new HashSet<ProductStockRecords>();
            this.WorderDepartments = new HashSet<WorderDepartments>();
            this.WorderRecipes = new HashSet<WorderRecipes>();
        }
    
        public int subWorderID { get; set; }
        public Nullable<System.DateTime> worderStartDate { get; set; }
        public Nullable<System.DateTime> worderFinishDate { get; set; }
        public int worderProgress { get; set; }
        public int subOrderID { get; set; }
        public int worderQuantity { get; set; }
        public int semiProductCount { get; set; }
        public int worderSemiProgress { get; set; }
        public int worderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStockRecords> ProductStockRecords { get; set; }
        public virtual subOrders subOrders { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorderDepartments> WorderDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorderRecipes> WorderRecipes { get; set; }
    }
}
