//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int supplierID { get; set; }
        public string supplierCompanyName { get; set; }
        public string supplierGSM { get; set; }
        public string supplierPhone { get; set; }
        public string supplierName { get; set; }
        public string supplierAddress { get; set; }
        public string supplierDescription { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> countryID { get; set; }
        public string taxNumber { get; set; }
        public string tcNumber { get; set; }
        public string supplierMailAddress { get; set; }
    }
}
