//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorderRecipes
    {
        public int worRecipeID { get; set; }
        public int worderID { get; set; }
        public int recipeID { get; set; }
        public int subWorderID { get; set; }
    
        public virtual Recipes Recipes { get; set; }
        public virtual subWork subWork { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
