//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordepMachines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WordepMachines()
        {
            this.WorDepMachMolds = new HashSet<WorDepMachMolds>();
            this.WorMachEmployees = new HashSet<WorMachEmployees>();
        }
    
        public int worMachID { get; set; }
        public int machineID { get; set; }
        public int worDepID { get; set; }
        public bool worMachStatus { get; set; }
        public int worMachProgress { get; set; }
        public Nullable<System.DateTime> worMachStartDate { get; set; }
        public Nullable<System.DateTime> worMachFinishDate { get; set; }
    
        public virtual Machines Machines { get; set; }
        public virtual WorderDepartments WorderDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorDepMachMolds> WorDepMachMolds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorMachEmployees> WorMachEmployees { get; set; }
    }
}
