//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorderEmpDayOffs
    {
        public int worEmpDoffID { get; set; }
        public int worMachEmpID { get; set; }
        public System.DateTime currentTime { get; set; }
        public string dayOffDescription { get; set; }
    
        public virtual WorMachEmployees WorMachEmployees { get; set; }
    }
}
