//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorDepMachMolds
    {
        public int machMoldID { get; set; }
        public int moldCountID { get; set; }
        public int worMachID { get; set; }
        public int worMoldCount { get; set; }
    
        public virtual MoldCounts MoldCounts { get; set; }
        public virtual WordepMachines WordepMachines { get; set; }
    }
}
