//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorderDepartments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorderDepartments()
        {
            this.WordepMachines = new HashSet<WordepMachines>();
        }
    
        public int worDepID { get; set; }
        public int worderID { get; set; }
        public int departmentID { get; set; }
        public int worDepProgress { get; set; }
        public bool worDepStatus { get; set; }
        public Nullable<System.DateTime> wordepStartDate { get; set; }
        public Nullable<System.DateTime> wordepFinishDate { get; set; }
        public Nullable<int> subWorderID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual subWork subWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordepMachines> WordepMachines { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
