//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrders()
        {
            this.MaterialStockRecords = new HashSet<MaterialStockRecords>();
            this.subWork = new HashSet<subWork>();
            this.WorderDepartments = new HashSet<WorderDepartments>();
            this.WorderRecipes = new HashSet<WorderRecipes>();
        }
    
        public int worderID { get; set; }
        public string worderContent { get; set; }
        public Nullable<System.DateTime> worderStartDate { get; set; }
        public Nullable<System.DateTime> worderFinishDate { get; set; }
        public int worderProgress { get; set; }
        public int worderStatus { get; set; }
        public int orderID { get; set; }
        public int worderQuantity { get; set; }
        public int semiProductCount { get; set; }
        public int worderSemiProgress { get; set; }
        public string worderDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStockRecords> MaterialStockRecords { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subWork> subWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorderDepartments> WorderDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorderRecipes> WorderRecipes { get; set; }
    }
}
