//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorMachEmpWorks
    {
        public int empWorkID { get; set; }
        public int dailyProductCount { get; set; }
        public int worMachEmpID { get; set; }
        public System.DateTime workDate { get; set; }
    
        public virtual WorMachEmployees WorMachEmployees { get; set; }
    }
}
