//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorMachEmployees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorMachEmployees()
        {
            this.WorderEmpDayOffs = new HashSet<WorderEmpDayOffs>();
            this.WorMachEmpWorks = new HashSet<WorMachEmpWorks>();
        }
    
        public int worMachEmpID { get; set; }
        public int empID { get; set; }
        public int worMachID { get; set; }
        public int employeeTotal { get; set; }
        public int dayOffCount { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual WordepMachines WordepMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorderEmpDayOffs> WorderEmpDayOffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorMachEmpWorks> WorMachEmpWorks { get; set; }
    }
}
